# pandas数据处理

In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series

## 1、删除重复元素

In [2]:
def make_df(index, cols):
    df = DataFrame({col: [col + str(i) for i in index] for col in cols})
    df.index = index
    return df

In [3]:
df = make_df([1, 2, 3, 4], list('ABCD'))
df

A   B   C   D
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4

In [5]:
df.loc[1] = df.loc[2]

In [6]:
df

A   B   C   D
1  A2  B2  C2  D2
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4

In [7]:
# 检测重复行
df.duplicated()

1    False
2     True
3    False
4    False
dtype: bool

In [10]:
~df.duplicated()

1     True
2    False
3     True
4     True
dtype: bool

In [12]:
df.loc[~df.duplicated()]

A   B   C   D
1  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4

In [11]:
df.duplicated(keep='last')

1     True
2    False
3    False
4    False
dtype: bool

In [14]:
df.drop_duplicates(keep='first')

A   B   C   D
1  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4

In [15]:
df.drop_duplicates(keep='last')

A   B   C   D
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4

In [16]:
df

A   B   C   D
1  A2  B2  C2  D2
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4

In [19]:
df.loc[1, 'D'] = 'D1'

In [20]:
df

A   B   C   D
1  A2  B2  C2  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4

In [21]:
df.duplicated()

1    False
2    False
3    False
4    False
dtype: bool

In [22]:
df.duplicated(subset=['A', 'B', 'C'])

1    False
2     True
3    False
4    False
dtype: bool

In [25]:
~df.duplicated(subset=['A', 'B', 'C'])

1     True
2    False
3     True
4     True
dtype: bool

In [24]:
# 逻辑运算
np.logical_not(df.duplicated(subset=['A', 'B', 'C']))

1     True
2    False
3     True
4     True
dtype: bool

## 2. 映射

In [26]:
# replace 对dataframe的values进行替换
index = ['张三', '李四', '赵六', '王五']
columns = ['语文', '数学', '英语', 'AI']
data = np.random.randint(0, 150, size=(4, 4))
df = DataFrame(index=index, columns=columns, data=data)
df

语文   数学   英语   AI
张三    8  119   98  141
李四   18   70   94   36
赵六   53  129  133  132
王五  132  141    9   98

### 1) replace()函数：替换元素

In [29]:
df.loc['张三', '数学'] = 8
df

语文   数学   英语   AI
张三    8    8   98  141
李四   18   70   94   36
赵六   53  129  133  132
王五  132  141    9   98

In [30]:
mapping = {8: 108, 9: 119, 18: 118, 36: 136}
df.replace(mapping)

语文   数学   英语   AI
张三  108  108   98  141
李四  118   70   94  136
赵六   53  129  133  132
王五  132  141  119   98

In [33]:
df.iloc[0, 0], df.iloc[0, 1] = np.nan, np.nan
df

语文     数学   英语   AI
张三    NaN    NaN   98  141
李四   18.0   70.0   94   36
赵六   53.0  129.0  133  132
王五  132.0  141.0    9   98

In [36]:
df.replace({np.nan: 0})

语文     数学   英语   AI
张三    0.0    0.0   98  141
李四   18.0   70.0   94   36
赵六   53.0  129.0  133  132
王五  132.0  141.0    9   98

### 2) map()函数：新建一列

In [37]:
df

语文     数学   英语   AI
张三    NaN    NaN   98  141
李四   18.0   70.0   94   36
赵六   53.0  129.0  133  132
王五  132.0  141.0    9   98

In [ ]:
# 新建一列最简单的方法是直接使用中括号的写法
df['综合'] = np.random.randint(0, 300, size=(4,))

In [39]:
mapping = {141: 111, 36: 136, 132: 132, 98: 108}
df['python'] = df['AI'].map(mapping)
df

语文     数学   英语   AI  python
张三    NaN    NaN   98  141     111
李四   18.0   70.0   94   36     136
赵六   53.0  129.0  133  132     132
王五  132.0  141.0    9   98     108

In [40]:
# 对已有的列进行修改
df['python'] = df['python'].map(lambda score: score - 50)
df

语文     数学   英语   AI  python
张三    NaN    NaN   98  141      61
李四   18.0   70.0   94   36      86
赵六   53.0  129.0  133  132      82
王五  132.0  141.0    9   98      58

In [41]:
# 传自定义的函数
def convert(score):
    if score >= 120:
        return '优秀'
    elif 120 > score >= 90:
        return '及格'
    else:
        return '不及格'

In [42]:
df['AI_score'] = df['AI'].map(convert)
df

语文     数学   英语   AI  python AI_score
张三    NaN    NaN   98  141      61       优秀
李四   18.0   70.0   94   36      86      不及格
赵六   53.0  129.0  133  132      82       优秀
王五  132.0  141.0    9   98      58       及格

In [43]:
df['AI_score2'] = df['AI'].transform(convert)
df

语文     数学   英语   AI  python AI_score AI_score2
张三    NaN    NaN   98  141      61       优秀        优秀
李四   18.0   70.0   94   36      86      不及格       不及格
赵六   53.0  129.0  133  132      82       优秀        优秀
王五  132.0  141.0    9   98      58       及格        及格

### 3) rename()函数：替换索引

In [ ]:
# rename是专门操作索引的. 

In [ ]:
# rename重命名, 就是对索引进行重命名. 

In [45]:
mapping = {'张三': 'Mr Zhang', '李四': 'Mr Lee', '王五': 'Mr Wang', '赵六': 'Mr Six'}
df.rename(index=mapping)

语文     数学   英语   AI  python AI_score AI_score2
Mr Zhang    NaN    NaN   98  141      61       优秀        优秀
Mr Lee     18.0   70.0   94   36      86      不及格       不及格
Mr Six     53.0  129.0  133  132      82       优秀        优秀
Mr Wang   132.0  141.0    9   98      58       及格        及格

## 3. 异常值检测和过滤

In [ ]:
# 异常值的检测和过滤思路:
1. 定义异常值的判断标准.  绝对值大于三倍标准偏差
2. 把判断标准写成条件写法. (df.abs() > 3 * df.std()).any(axis=1)
3. 使用条件去过滤          df.loc[~cond]

In [46]:
df = DataFrame(data=np.random.randn(10000, 3))
df

0         1         2
0     0.394085  0.011354  1.194485
1     0.259045 -1.755286 -0.892917
2    -0.492840 -0.243823  0.309943
3    -0.984889 -1.066494  0.226560
4     1.114539  1.083985  0.083271
...        ...       ...       ...
9995  0.037311  0.577110  0.009724
9996 -0.409854 -1.604657 -1.294382
9997  1.506104  0.040682  0.064233
9998 -0.840723 -0.392282  0.676297
9999  0.098663 -2.353112  0.241300

[10000 rows x 3 columns]

In [48]:
# describe函数查看每一列的描述性统计量
df.describe()

0             1             2
count  10000.000000  10000.000000  10000.000000
mean      -0.002648      0.001919     -0.010498
std        0.998964      0.998281      1.006547
min       -3.687844     -3.720401     -4.312781
25%       -0.683445     -0.671532     -0.680419
50%       -0.013722     -0.001953     -0.014441
75%        0.684812      0.655091      0.656335
max        4.095145      3.915535      3.651737

In [51]:
df.std()

0    0.998964
1    0.998281
2    1.006547
dtype: float64

In [54]:
# absolute : 绝对值
# 默认的dataframe和series运算规则是series的index和dataframe的columns进行对比, 索引相同的位置, 进行运算. 
# 实现的效果就相当于dataframe的每一行和整个series进行运算. 
cond = (df.abs() > 3 * df.std()).any(axis=1)

In [136]:
cond

0       False
1       False
2       False
3       False
4       False
        ...  
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [56]:
df.loc[~cond]

0         1         2
0     0.394085  0.011354  1.194485
1     0.259045 -1.755286 -0.892917
2    -0.492840 -0.243823  0.309943
3    -0.984889 -1.066494  0.226560
4     1.114539  1.083985  0.083271
...        ...       ...       ...
9995  0.037311  0.577110  0.009724
9996 -0.409854 -1.604657 -1.294382
9997  1.506104  0.040682  0.064233
9998 -0.840723 -0.392282  0.676297
9999  0.098663 -2.353112  0.241300

[9924 rows x 3 columns]

## 4. 抽样

### 随机抽样

In [58]:
index = ['张三', '李四', '赵六', '王五']
columns = ['语文', '数学', '英语', 'AI']
data = np.random.randint(0, 150, size=(4, 4))
df = DataFrame(index=index, columns=columns, data=data)
df

语文   数学   英语   AI
张三   24  126   63    8
李四   64  114  137   46
赵六  116  145   48  113
王五  103  116  132   71

In [61]:
# 有放回抽样
df.take([0, 1, 2, 3, 1, 2, 3, 1, 1, 2, 2, ])

语文   数学   英语   AI
张三   24  126   63    8
李四   64  114  137   46
赵六  116  145   48  113
王五  103  116  132   71
李四   64  114  137   46
赵六  116  145   48  113
王五  103  116  132   71
李四   64  114  137   46
李四   64  114  137   46
赵六  116  145   48  113
赵六  116  145   48  113

In [87]:
np.random.randint(0, 4, size=(4, ))

array([3, 1, 0, 0])

In [88]:
# 借助np.random.randint可以实现有放回抽样
df.take(np.random.randint(0, 4, size=(4, )))

语文   数学   英语   AI
王五  103  116  132   71
张三   24  126   63    8
王五  103  116  132   71
赵六  116  145   48  113

In [104]:
# 无放回抽样. 
# permutation排列组合
np.random.permutation([0, 1, 2, 3])

array([3, 0, 2, 1])

In [112]:
# 借助np.random.permutation实现无放回抽样
df.take(np.random.permutation([0, 1, 2, 3]))

语文   数学   英语   AI
王五  103  116  132   71
赵六  116  145   48  113
李四   64  114  137   46
张三   24  126   63    8

In [126]:
df.take(np.random.permutation([0, 1, 2, 3])[:3])

语文   数学   英语  AI
李四   64  114  137  46
张三   24  126   63   8
王五  103  116  132  71

In [135]:
df.take(np.random.randint(0, 4, size=(4, ))[: 3])

语文   数学   英语  AI
王五  103  116  132  71
王五  103  116  132  71
张三   24  126   63   8

## 5. 数据聚合【重点】

In [137]:
df = DataFrame({'color':['red','white','red','cyan','cyan','green','white','cyan'],
                'price':np.random.randint(0,8,size = 8),
                'weight':np.random.randint(50,55,size = 8)})
df

color  price  weight
0    red      7      52
1  white      7      54
2    red      1      50
3   cyan      0      50
4   cyan      6      53
5  green      5      52
6  white      6      54
7   cyan      3      50

In [138]:
df.groupby(by='color')

In [141]:
df.groupby(by=['color', 'price']).groups

{('cyan', 0): [3], ('cyan', 3): [7], ('cyan', 6): [4], ('green', 5): [5], ('red', 1): [2], ('red', 7): [0], ('white', 6): [6], ('white', 7): [1]}

In [139]:
df.groupby(by='color').groups

{'cyan': [3, 4, 7], 'green': [5], 'red': [0, 2], 'white': [1, 6]}

In [145]:
# 分组之后, 对分组的数据进行聚合
# 先聚合, 再取数据
df.groupby(by='color').mean()[['price']]

price
color       
cyan     3.0
green    5.0
red      4.0
white    6.5

In [147]:
# 先取数据, 再聚合
# 运算量比较少, 只对price进行了聚合. 
# 在遇到比较大的dataframe的时候, 推荐这种写法. 
price_mean = df.groupby(by='color')[['price']].mean()

In [148]:
display(df, price_mean)

color  price  weight
0    red      7      52
1  white      7      54
2    red      1      50
3   cyan      0      50
4   cyan      6      53
5  green      5      52
6  white      6      54
7   cyan      3      50

price
color       
cyan     3.0
green    5.0
red      4.0
white    6.5

In [149]:
# 经过观察发现, 原始dataframe的color列和price_mean的index相同, 可以进行合并. 
pd.merge(df, price_mean, left_on='color', right_index=True, suffixes=['', '_mean'])

color  price  weight  price_mean
0    red      7      52         4.0
2    red      1      50         4.0
1  white      7      54         6.5
6  white      6      54         6.5
3   cyan      0      50         3.0
4   cyan      6      53         3.0
7   cyan      3      50         3.0
5  green      5      52         5.0

In [151]:
np.random.randint(0, 100, size=10)

array([30,  0, 25, 55, 62, 68, 63, 47, 77, 55])

In [152]:
np.random.rand(10)

array([0.40676872, 0.15005448, 0.50845541, 0.24594461, 0.88979446,
       0.00600089, 0.94194889, 0.22709119, 0.58088347, 0.887608  ])

In [153]:
ddd = DataFrame({
    'item': ['萝卜', '萝卜', '萝卜', '白菜','白菜', '辣椒', '辣椒', '辣椒', '冬瓜', '冬瓜'],
    'color': ['白', '青', '红', '白', '青', '白', '青', '红', '白', '青'],
    'weight': np.random.randint(0, 100, size=10),
    'price': np.random.rand(10) * 10
})
ddd

item color  weight     price
0   萝卜     白      25  2.721281
1   萝卜     青      71  8.692669
2   萝卜     红      44  3.279895
3   白菜     白       2  7.930781
4   白菜     青      34  2.262053
5   辣椒     白      40  0.229559
6   辣椒     青      95  4.377616
7   辣椒     红       7  0.586074
8   冬瓜     白      34  7.784422
9   冬瓜     青      20  4.671031

In [156]:
# 求出颜色为白色的价格总和
ddd.groupby(by='color')[['price']].sum()

price
color           
白      18.666045
红       3.865969
青      20.003368

In [159]:
# 求出萝卜的所有重量(包括白萝卜，胡萝卜，青萝卜）以及平均价格
weight_sum = ddd.groupby(by='item')[['weight']].sum()

In [161]:
weight_sum

weight
item        
冬瓜        54
白菜        36
萝卜       140
辣椒       142

In [160]:
price_mean = ddd.groupby(by='item')[['price']].mean()

In [163]:
# 使用merge合并总重量及平均价格
ddd = ddd.merge(weight_sum, left_on='item', right_index=True, suffixes=['', '_sum'])

In [164]:
ddd.merge(price_mean, left_on='item', right_index=True, suffixes=['', '_mean'])

item color  weight     price  weight_sum  price_mean
0   萝卜     白      25  2.721281         140    4.897949
1   萝卜     青      71  8.692669         140    4.897949
2   萝卜     红      44  3.279895         140    4.897949
3   白菜     白       2  7.930781          36    5.096417
4   白菜     青      34  2.262053          36    5.096417
5   辣椒     白      40  0.229559         142    1.731083
6   辣椒     青      95  4.377616         142    1.731083
7   辣椒     红       7  0.586074         142    1.731083
8   冬瓜     白      34  7.784422          54    6.227727
9   冬瓜     青      20  4.671031          54    6.227727

## 6.0 高级数据聚合

In [168]:
price_mean = price_mean.add_prefix('mean_')

In [169]:
ddd.merge(price_mean, left_on='item', right_index=True)

item color  weight     price  weight_sum  mean_price
0   萝卜     白      25  2.721281         140    4.897949
1   萝卜     青      71  8.692669         140    4.897949
2   萝卜     红      44  3.279895         140    4.897949
3   白菜     白       2  7.930781          36    5.096417
4   白菜     青      34  2.262053          36    5.096417
5   辣椒     白      40  0.229559         142    1.731083
6   辣椒     青      95  4.377616         142    1.731083
7   辣椒     红       7  0.586074         142    1.731083
8   冬瓜     白      34  7.784422          54    6.227727
9   冬瓜     青      20  4.671031          54    6.227727

### 可以使用transform和apply实现相同功能

In [171]:
ddd.groupby(by='item')[['weight']].transform(sum)

weight
0     140
1     140
2     140
3      36
4      36
5     142
6     142
7     142
8      54
9      54

In [172]:
ddd.groupby(by='item')[['weight']].apply(sum)

weight
item        
冬瓜        54
白菜        36
萝卜       140
辣椒       142